name: Fetch Open Pull Requests and Markdown Files

on:
  schedule:
    - cron: "0 0 * * *" # 毎日UTC 00:00（日本時間 09:00）に実行
  workflow_dispatch: # 手動実行も可能

jobs:
  fetch-prs-and-md-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: GitHub API からオープンな PR を取得
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/nostr-protocol/nips/pulls?state=open" | jq '.' > pull_requests.json

      - name: 除外リスト（exclude_files.json）を作成
        run: |
          echo '["BREAKING.md", "README.md"]' > exclude_files.json

      - name: GitHub API から .md ファイルを取得し、除外リストを適用
        run: |
          # リモートリポジトリのルートにある .md ファイルを取得
          MD_FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/nostr-protocol/nips/contents?ref=master")

          # 除外リストを適用
          jq --argjson exclude "$(cat exclude_files.json)" \
            '[.[] | select(.name | endswith(".md") and (.name | inside($exclude) | not)) | .name]' \
            <<< "$MD_FILES" > md_files.json

      - name: md_files.json が生成されたか確認
        run: |
          if [[ ! -f md_files.json ]]; then
            echo "Error: md_files.json was not created."
            exit 1
          else
            echo "md_files.json was successfully created."
            cat md_files.json  # デバッグ用に中身を出力
          fi

      - name: 変更があればコミットしてプッシュ
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git checkout main # main ブランチに切り替え

          # 変更があれば commit
          git add pull_requests.json md_files.json exclude_files.json
          if [[ `git status --porcelain` ]]; then
            git commit -m "Update open pull requests list and markdown files list"
            git push origin main --force
          else
            echo "No changes detected, skipping commit."
          fi
