name: Random NIPs

on:
  workflow_dispatch: # 手動実行を可能にする
  schedule:
    - cron: "45 */2 * * *" # 2時間ごとに実行

jobs:
  select-md-file:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: nip_list.json の存在確認
        run: |
          if [ ! -f nip_list.json ]; then
            echo "nip_list.json が見つかりません"
            exit 1
          fi

      - name: nip_list.json からランダムな NIP を選択
        id: select_nip
        run: |
          # nip_list.json を jq で読み込み、ランダムなインデックスを選ぶ
          selected_nip=$(jq -r '.[(rand * length) | floor | int] | {title, file, url}' nip_list.json)
          
          # 各フィールドを環境変数に設定
          title=$(echo "$selected_nip" | jq -r '.title')
          file=$(echo "$selected_nip" | jq -r '.file')
          url=$(echo "$selected_nip" | jq -r '.url')

          # 環境変数に設定
          echo "title=$title" >> $GITHUB_ENV
          echo "file=$file" >> $GITHUB_ENV
          echo "url=$url" >> $GITHUB_ENV

      - name: 選ばれたファイルを表示
        run: echo "ランダムに選ばれたファイルは ${{ env.title }} です"

      - name: Nostr に投稿する
        uses: snow-actions/nostr@v1.8.1
        timeout-minutes: 1
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          content: |
            ${{ env.title }}
            ${{ env.url }}
        id: publish
