name: Random Pull Request Information

on:
  workflow_dispatch: # 手動実行を有効にする
  schedule:
    - cron: "45 1-23/2 * * *" # 時〜23時の間で2時間おき＝奇数時毎

jobs:
  pr-info:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: pull_requests.json を読み込む
        id: generate
        run: |
          # pull_requests.json を読み込む
          PR_JSON=$(cat pull_requests.json)

          # PR の数を取得
          PR_COUNT=$(echo "$PR_JSON" | jq 'length')

          if [ "$PR_COUNT" -eq 0 ]; then
            echo "No open pull requests found."
            exit 1
          fi

          # ランダムなインデックスを取得
          RANDOM_INDEX=$((RANDOM % PR_COUNT))

          # ランダムなプルリクエストを選択
          SELECTED_PR=$(echo "$PR_JSON" | jq ".[$RANDOM_INDEX]")

          # PR 情報を出力
          PR_NUMBER=$(echo "$SELECTED_PR" | jq -r '.number')
          TITLE=$(echo "$SELECTED_PR" | jq -r '.title')
          USER=$(echo "$SELECTED_PR" | jq -r '.user.login')
          URL=$(echo "$SELECTED_PR" | jq -r '.html_url')

          echo "number=$PR_NUMBER" >> $GITHUB_ENV
          echo "title=$TITLE" >> $GITHUB_ENV
          echo "user=$USER" >> $GITHUB_ENV
          echo "url=$URL" >> $GITHUB_ENV

      - name: 選ばれた PR を表示
        run: |
          echo "選ばれたプルリクエストの情報:"
          echo "プルリクエスト番号: ${{ env.number }}"
          echo "タイトル: ${{ env.title }}"
          echo "作成者: ${{ env.user }}"
          echo "URL: ${{ env.url }}"

      - name: Nostr に投稿する
        uses: snow-actions/nostr@v1.8.1
        timeout-minutes: 1
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          content: |
            Pick a Random Open PR #${{ env.number }}
            タイトル: ${{ env.title }}
            作成者: ${{ env.user }}
            URL: ${{ env.url }}
        id: publish
