name: Select Random NIPs Markdown File

on:
  workflow_dispatch: # 手動実行を可能にする
  schedule:
    - cron: "45 */2 * * *" # 2時間ごとに実行

jobs:
  select-md-file:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: md_files.json を読み込む
        run: |
          # md_files.json と exclude_files.json を読み込む
          MD_FILES=$(cat md_files.json | jq -r '.[]')
          EXCLUDE_FILES=$(cat exclude_files.json | jq -r '.[]')

          # 除外リストに含まれない .md ファイルを取得
          FILTERED_FILES=$(echo "$MD_FILES" | grep -Fxv -f <(echo "$EXCLUDE_FILES"))

          # ランダムで1つ選択
          RANDOM_FILE=$(echo "$FILTERED_FILES" | shuf -n 1)

          # 拡張子 .md を取り除く
          NIP_NUMBER=$(basename "$RANDOM_FILE" .md)

          # 選ばれたファイルとNIP番号を出力
          echo "選ばれたファイル: $RANDOM_FILE"
          echo "nip_number=$NIP_NUMBER" >> $GITHUB_ENV

      - name: 選ばれたファイルを表示
        run: echo "ランダムに選ばれたファイルは ${{ env.nip_number }} です"

      - name: Nostr に投稿する
        uses: snow-actions/nostr@v1.8.1
        timeout-minutes: 1
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          content: |
            NIP:${{ env.nip_number }}
            URL: https://github.com/nostr-protocol/nips/blob/master/${{ env.nip_number }}.md
        id: publish
